# Generated by Django 5.2.8 on 2025-12-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='place',
        ),
    ]
